<h3>Data Mahasiswa</h3>

In [2]:
import pandas as pd
import numpy as np
import random

# Jumlah baris data
jumlah_mahasiswa = 10000

# Data untuk disimulasikan
nama_depan = ['Adi', 'Budi', 'Citra', 'Dina', 'Eka', 'Fajar', 'Gita', 'Hari', 'Indah', 'Joko']
nama_belakang = ['Santoso', 'Wijaya', 'Putri', 'Saputra', 'Nugroho', 'Wibowo']
mata_kuliah = ['Struktur Data', 'Algoritma', 'Kecerdasan Buatan', 'Jaringan Komputer', 'Pemrograman Web', 'Sistem Operasi']
asal_daerah = ['Jakarta', 'Bandung', 'Surabaya', 'Yogyakarta', 'Medan', 'Makassar']

# Generate Data
np.random.seed(42)  # reproducibility
data = {
    'NIM': ['IF' + str(i).zfill(6) for i in range(1, jumlah_mahasiswa + 1)],
    'Nama': [random.choice(nama_depan) + ' ' + random.choice(nama_belakang) for _ in range(jumlah_mahasiswa)],
    'Jenis Kelamin': np.random.choice(['L', 'P'], jumlah_mahasiswa),
    'Umur': np.random.randint(17, 26, jumlah_mahasiswa),
    'Tahun Masuk': np.random.choice([2019, 2020, 2021, 2022, 2023], jumlah_mahasiswa),
    'IPK': np.round(np.random.normal(3.0, 0.4, jumlah_mahasiswa), 2),
    'Mata Kuliah Favorit': np.random.choice(mata_kuliah, jumlah_mahasiswa),
    'Keaktifan Organisasi': np.random.randint(0, 11, jumlah_mahasiswa),
    'Status Beasiswa': np.random.choice([True, False], jumlah_mahasiswa, p=[0.3, 0.7]),
    'Status Kelulusan': np.random.choice(['Lulus', 'Belum Lulus'], jumlah_mahasiswa, p=[0.4, 0.6]),
    'Jam Belajar per Hari': np.round(np.random.normal(2.5, 1.0, jumlah_mahasiswa), 2),
    'Domisili': np.random.choice(asal_daerah, jumlah_mahasiswa)
}

# Membuat DataFrame
df = pd.DataFrame(data)

# Memastikan nilai IPK dan Jam Belajar berada pada rentang yang valid
df['IPK'] = df['IPK'].clip(lower=0.0, upper=4.0)
df['Jam Belajar per Hari'] = df['Jam Belajar per Hari'].clip(lower=0.0)

# Menampilkan informasi dasar
print("Head of Data:")
print(df.head())

print("\nInfo:")
print(df.info())

print("\nDescriptive Statistics:")
print(df.describe(include='all'))

# Contoh Karakteristik Data
print("\nDistribusi Jenis Kelamin:")
print(df['Jenis Kelamin'].value_counts())

print("\nDistribusi Mata Kuliah Favorit:")
print(df['Mata Kuliah Favorit'].value_counts())

print("\nRata-rata IPK per Tahun Masuk:")
print(df.groupby('Tahun Masuk')['IPK'].mean())

Head of Data:
        NIM           Nama Jenis Kelamin  Umur  Tahun Masuk   IPK  \
0  IF000001     Joko Putri             L    19         2022  2.73
1  IF000002    Fajar Putri             P    24         2019  3.48
2  IF000003   Budi Saputra             L    23         2023  3.03
3  IF000004  Indah Saputra             L    19         2023  3.30
4  IF000005  Indah Nugroho             L    22         2023  3.61

  Mata Kuliah Favorit  Keaktifan Organisasi  Status Beasiswa Status Kelulusan  \
0      Sistem Operasi                     4             True            Lulus
1           Algoritma                     3            False            Lulus
2   Jaringan Komputer                     2            False            Lulus
3   Jaringan Komputer                     0            False      Belum Lulus
4           Algoritma                     7            False            Lulus

   Jam Belajar per Hari    Domisili
0                  3.55       Medan
1                  3.88    Makassar
2                  2.65       Medan
3                  2.53  Yogyakarta
4                  3.60       Medan

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   NIM                   10000 non-null  object
 1   Nama                  10000 non-null  object
 2   Jenis Kelamin         10000 non-null  object
 3   Umur                  10000 non-null  int32
 4   Tahun Masuk           10000 non-null  int32
 5   IPK                   10000 non-null  float64
 6   Mata Kuliah Favorit   10000 non-null  object
 7   Keaktifan Organisasi  10000 non-null  int32
 8   Status Beasiswa       10000 non-null  bool
 9   Status Kelulusan      10000 non-null  object
 10  Jam Belajar per Hari  10000 non-null  float64
 11  Domisili              10000 non-null  object
dtypes: bool(1), float64(2), int32(3), object(6)
memory usage: 752.1+ KB
None

Descriptive Statistics:
             NIM         Nama Jenis Kelamin         Umur   Tahun Masuk  \
count      10000        10000         10000  10000.00000  10000.000000
unique     10000           60             2          NaN           NaN
top     IF000001  Budi Wijaya             L          NaN           NaN
freq           1          195          5013          NaN           NaN
mean         NaN          NaN           NaN     20.97980   2021.019400
std          NaN          NaN           NaN      2.58311      1.418529
min          NaN          NaN           NaN     17.00000   2019.000000
25%          NaN          NaN           NaN     19.00000   2020.000000
50%          NaN          NaN           NaN     21.00000   2021.000000
75%          NaN          NaN           NaN     23.00000   2022.000000
max          NaN          NaN           NaN     25.00000   2023.000000

                 IPK Mata Kuliah Favorit  Keaktifan Organisasi  \
count   10000.000000               10000          10000.000000
unique           NaN                   6                   NaN
top              NaN      Sistem Operasi                   NaN
freq             NaN                1682                   NaN
mean        2.998745                 NaN              4.999900
std         0.394710                 NaN              3.144406
min         1.460000                 NaN              0.000000
25%         2.730000                 NaN              2.000000
50%         3.000000                 NaN              5.000000
75%         3.270000                 NaN              8.000000
max         4.000000                 NaN             10.000000

       Status Beasiswa Status Kelulusan  Jam Belajar per Hari    Domisili
count            10000            10000          10000.000000       10000
unique               2                2                   NaN           6
top              False      Belum Lulus                   NaN  Yogyakarta
freq              7073             5980                   NaN        1702
mean               NaN              NaN              2.494520         NaN
std                NaN              NaN              0.996124         NaN
min                NaN              NaN              0.000000         NaN
25%                NaN              NaN              1.820000         NaN
50%                NaN              NaN              2.480000         NaN
75%                NaN              NaN              3.160000         NaN
max                NaN              NaN              6.160000         NaN

Distribusi Jenis Kelamin:
Jenis Kelamin
L    5013
P    4987
Name: count, dtype: int64

Distribusi Mata Kuliah Favorit:
Mata Kuliah Favorit
Sistem Operasi       1682
Kecerdasan Buatan    1679
Pemrograman Web      1671
Algoritma            1668
Struktur Data        1657
Jaringan Komputer    1643
Name: count, dtype: int64

Rata-rata IPK per Tahun Masuk:
Tahun Masuk
2019    3.006425
2020    3.018457
2021    2.990668
2022    2.987713
2023    2.991141
Name: IPK, dtype: float64